// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMWJ_lltKWKKh83iWKYUn0KyC0p4Pheao',
    appId: '1:1028762535815:web:359e139cd36af7ff40b522',
    messagingSenderId: '1028762535815',
    projectId: 'rico-my-lesson',
    authDomain: 'rico-my-lesson.firebaseapp.com',
    storageBucket: 'rico-my-lesson.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDm0i_GNAJl-HjL4yNI8y7X-voYxaEzdhU',
    appId: '1:1028762535815:android:e35809cf0ae157b440b522',
    messagingSenderId: '1028762535815',
    projectId: 'rico-my-lesson',
    storageBucket: 'rico-my-lesson.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkREdCsHtDaLh4TSTM13a8bSg4mLlGZlM',
    appId: '1:1028762535815:ios:14b55d76e42a878e40b522',
    messagingSenderId: '1028762535815',
    projectId: 'rico-my-lesson',
    storageBucket: 'rico-my-lesson.appspot.com',
    iosClientId: '1028762535815-663d4dm6sg9hatpnc2e79m74mftm0le1.apps.googleusercontent.com',
    iosBundleId: 'com.example.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkREdCsHtDaLh4TSTM13a8bSg4mLlGZlM',
    appId: '1:1028762535815:ios:14b55d76e42a878e40b522',
    messagingSenderId: '1028762535815',
    projectId: 'rico-my-lesson',
    storageBucket: 'rico-my-lesson.appspot.com',
    iosClientId: '1028762535815-663d4dm6sg9hatpnc2e79m74mftm0le1.apps.googleusercontent.com',
    iosBundleId: 'com.example.mynotes',
  );
}
